### ISSUE TITLE
Image cannot contain children

### ISSUE THREAD

**Issue by alvarogonjim** [brh55/react-native-hero#10]
Hello, I followed the guide on Github and use the code:
  
<Hero
     source={{uri: 'http://helloworld.com/1.jpeg'}}
     renderOverlay={() => (
       <View>
           <Text>React Native Hero!</Text>
           <Text>Is super duper, cool!</Text>
       </View>
     )} />

but I have the Error: The <Image> component cannot contain children. If you want to render content on the top of the image, consider using absolute positioning. 

Thanks ;)

**Comment by smooJitter** [comment]
Well 'React Native Hero!'   is not a component.  I haven't used this yet but maybe you should try something like 
<View><Text>React Native Hero!</Text></View>

**Comment by alvarogonjim** [comment]
@smooJitter I don't understand what you mean. I imported Hero from react-native-hero.
The problem is I cannot use `<Text>` inside of a `<Image>` I will attach a screenshot of the error so you can understand it better.
![screenshot_20171122-114206](https://user-images.githubusercontent.com/25668523/33123426-76aa0cfe-cf7a-11e7-9274-fab13fb920f8.png)

**Comment by brh55** [comment]
@smooJitter - There was github automatically renders the tags in the issue content.
@alvarogonjim - Looks like there was a recent changes in the `<Image>` component in the latest version of RN that has deprecated children within `Image`. I'll need to look at a update (currently abroad) unless someone wants to tackle this.

**Comment by alvarogonjim** [comment]
@brh55 May you give me an example how to use absolute positioning? I just want to put a Text over a Image.

**Comment by brh55** [comment]
You need to have a parent element wrapper that is set to relative. The parent elements position in relation to the other elements (it's origins) will then become baseline for any absolute children elements. In this case I would assume you would have 2 children elements `<Overlay><Image>` and 1 parrent `<View>`.

So your base structure:
```
<View style={styles.parentWrapper}> // Parent
    <Overlay style={styles.childOverlay}/>
    <Image style={styles.imageBase}/>
</View>
```

The styles would most likely follow:
```
const styles = StyleSheet.create({
    parentWrapper: {
      position: 'relative',
    },
    childOverlay: {
       position: 'absolute',
       left: 0,  // "top" and "left" might not be necessary as RN may have these set to 0 by default
       top: 0,
      zIndex: 2, // On top of image
    },
  imageBase: {
     position: 'absolute',
     left: 0,
     top: 0,
     zIndex: 1 // below overlay
   }
}
```

Something like this should theoretically work, sorry my CSS is a bit rusty these days. :)

**Comment by brh55** [comment]
#11 fixes these issues, thanks for your contribution!
