### ISSUE TITLE
Updating image bug

### ISSUE THREAD

**Issue by ilinski** [brh55/react-native-hero#12]
Hi guys,

In Hero.js:

	componentWillReceiveProps(nextProps) {
		console.log ('receive props hero')
		if (nextProps.source !== this.props.source) {
			this.setState({
				source: this.props.source
			});
		}
	};
It should be source: nextProps.source, or it never updates the image on rerendering parent component.

**Comment by brh55** [comment]
@ilinski,

I see what you are saying, you are right it should be `this.state.source !== nextProps.source`, if you feel comfortable submitting a PR, you can send one this way. 💃

**Comment by ilinski** [comment]
That's not what I meant, it should be

this.setState({
			source: nextProps.source
		});

**Comment by brh55** [comment]
@ilinski Ohhh. Yes you are correct, would you be open to submitting a PR? Otherwise, I'll go ahead and fix it.

**Comment by ilinski** [comment]
Please fix it yourself, I'm not really familiar with gitflow, so it will be way more easy for you. :) Thanks for your work.

**Comment by brh55** [comment]
@ilinski Thanks for the contribution :). Went ahead and fixed the bug, you should now see the fix at v0.3.1
